#include <cstdint>
#include <cstdlib>
#include <list>
#include <optional>
#include <set>
#include <utility>

std::uint64_t add(const std::uint64_t &arg1, const std::uint64_t &arg2);

template<typename T1>
std::list<T1> app(std::list<T1> arg1, std::list<T1> arg2) {
    // app Nil ys = ys
    if (arg1.empty()) {
        return arg2;
    }

    // app (Cons x xs) ys = Cons x (app xs ys)
    auto x = arg1.front();
    arg1.erase(arg1.begin(), std::next(arg1.begin(), 1));
    auto xs = std::move(arg1);
    auto temp0 = app(std::move(xs), std::move(arg2));
    temp0.push_front(x);
    return temp0;
}

template<typename T1>
std::list<T1> rev(std::list<T1> arg1) {
    // rev Nil = Nil
    if (arg1.empty()) {
        return std::list<T1>();
    }

    // rev (Cons x xs) = app (rev xs) (Cons x Nil)
    auto x = arg1.front();
    arg1.erase(arg1.begin(), std::next(arg1.begin(), 1));
    auto xs = std::move(arg1);
    auto temp0 = std::list<T1>();
    temp0.push_front(x);
    return app(rev(std::move(xs)), std::move(temp0));
}

template<typename T1>
std::list<T1> rev2(std::list<T1> arg1) {
    // rev2 Nil = Nil
    if (arg1.empty()) {
        return std::list<T1>();
    }

    // rev2 (x # xs) = (rev2 xs) @ (x # Nil)
    auto x = arg1.front();
    arg1.erase(arg1.begin(), std::next(arg1.begin(), 1));
    auto xs = std::move(arg1);
    auto temp0 = std::list<T1>();
    temp0.push_front(x);
    auto temp1 = rev2(std::move(xs));
    auto temp2 = std::move(temp0);
    temp1.splice(temp1.end(), temp2);
    return temp1;
}

template<typename T1>
std::list<T1> rev3(std::list<T1> arg1) {
    // rev3 [] = []
    if (arg1.empty()) {
        return std::list<T1>();
    }

    // rev3 (x # xs) = (rev3 xs) @ [x]
    auto x = arg1.front();
    arg1.erase(arg1.begin(), std::next(arg1.begin(), 1));
    auto xs = std::move(arg1);
    auto temp0 = rev3(std::move(xs));
    auto temp1 = std::list<T1>{x};
    temp0.splice(temp0.end(), temp1);
    return temp0;
}

template<typename T1>
std::optional<std::list<T1>> testoption(const std::optional<T1> &arg1) {
    // testoption None = Some Nil
    if (!arg1.has_value()) {
        return std::make_optional<std::list<T1>>(std::list<T1>());
    }

    // testoption (Some x) = Some [x]
    auto x = arg1.value();
    return std::make_optional<std::list<T1>>(std::list<T1>{x});
}

template<typename T1>
std::set<T1> testset(std::list<T1> arg1) {
    // testset Nil = {}
    if (arg1.empty()) {
        return std::set<T1>();
    }

    // testset (x # xs) = {x} \<inter> testset(xs)
    if (arg1.size() >= 1) {
        auto x = arg1.front();
        arg1.erase(arg1.begin(), std::next(arg1.begin(), 1));
        auto xs = std::move(arg1);
        auto temp0 = std::set<T1>{x};
        auto temp1 = testset(std::move(xs));
        temp0.merge(temp1);
        return temp1;
    }

    // testset (x # xs) = {x} \<union> testset(xs)
    auto x = arg1.front();
    arg1.erase(arg1.begin(), std::next(arg1.begin(), 1));
    auto xs = std::move(arg1);
    auto temp0 = std::set<T1>{x};
    auto temp1 = testset(std::move(xs));
    temp0.merge(temp1);
    return temp0;
}

template<typename T1>
std::list<T1> testifelse(std::list<T1> arg1, const T1 &arg2) {
    // testifelse [] n = []
    if (arg1.empty()) {
        return std::list<T1>();
    }

    // testifelse (x # xs) n = (if (x < n) then [x] else []) @ (testifelse xs n)
    auto x = arg1.front();
    arg1.erase(arg1.begin(), std::next(arg1.begin(), 1));
    auto xs = std::move(arg1);
    std::list<T1> temp0;
    if (x < arg2) {
        temp0 = std::list<T1>{x};
    } else {
        temp0 = std::list<T1>();
    }
    auto temp1 = temp0;
    auto temp2 = testifelse(std::move(xs), arg2);
    temp1.splice(temp1.end(), temp2);
    return temp1;
}

template<typename T1, typename T2>
std::pair<T1, T2> pair(const T1 &arg1, const T2 &arg2) {
    // pair f s = (f, s)
    return std::make_pair(arg1, arg2);
}

template<typename T1, typename T2>
T1 fst(const std::pair<T1, T2> &arg1) {
    // fst (first, second) = first
    auto first = arg1.first;
    return first;
}

template<typename T1, typename T2>
T2 snd(const std::pair<T1, T2> &arg1) {
    // snd (first, second) = second
    auto second = arg1.second;
    return second;
}

bool evn(const std::uint64_t &arg1);

std::uint64_t fib(const std::uint64_t &arg1);

std::uint64_t fact(const std::uint64_t &arg1);

bool altrue(const std::uint64_t &arg1);

// generated by HOL2Cpp
