#include "memoize.hpp"

std::uint64_t fib(const std::uint64_t &arg1) {
    auto impl = [&]() -> std::uint64_t {
        // fib 0 = 1
        if (arg1 == 0) {
            return 1;
        }

        // fib (Suc 0) = 1
        if (arg1 != 0) {
            if (arg1 - 1 == 0) {
                return 1;
            }
        }

        // fib n = (fib (n - 1)) + (fib (n - 2))
        return fib(arg1 - 1) + fib(arg1 - 2);
    };

    static std::map<std::tuple<std::uint64_t>, std::uint64_t> cache;
    auto args = std::make_tuple(arg1);
    auto it = cache.find(args);
    return it != cache.end() ? it->second : (cache.emplace(std::move(args), impl()).first->second);
}

std::uint64_t fact(const std::uint64_t &arg1) {
    auto impl = [&]() -> std::uint64_t {
        // fact 0 = 1
        if (arg1 == 0) {
            return 1;
        }

        // fact n = n * (fact (n - 1))
        return arg1 * fact(arg1 - 1);
    };

    static std::map<std::tuple<std::uint64_t>, std::uint64_t> cache;
    auto args = std::make_tuple(arg1);
    auto it = cache.find(args);
    return it != cache.end() ? it->second : (cache.emplace(std::move(args), impl()).first->second);
}

// generated by HOL2Cpp
