#include <cstdint>
#include <cstdlib>
#include <deque>

template<typename T1>
std::uint64_t test(std::deque<T1> arg1) {
    // test Nil = 0
    if (arg1.empty()) {
        return 0;
    }

    // test (Cons x xs) = length (If ((length xs) = 0) Nil xs) + 1
    arg1.erase(arg1.begin(), arg1.begin() + 1);
    auto xs = std::move(arg1);
    std::deque<T1> temp0;
    if (xs.size() == 0) {
        temp0 = std::deque<T1>();
    } else {
        temp0 = std::move(xs);
    }
    return temp0.size() + 1;
}

// generated by HOL2Cpp
