#include "typedef.hpp"

alsit<std::uint64_t> listwithlen(const UNKNOWN_TYPE &arg1) {
    // listwithlen 0 = sNil
    if (arg1 == 0) {
        return alsit<std::uint64_t>::aNil();
    }

    // listwithlen (Suc n) = sCons 1 (listwithlen n)
    auto n = arg1 - 1;
    auto temp0 = alsit<std::uint64_t>::aCons(
        1, listwithlen(n)
    );
    return temp0;
}

// generated by HOL2Cpp
