#include <cstdint>
#include <cstdlib>
#include <deque>
#include <memory>
#include <set>
#include <variant>

template<typename T1>
class atree {
    struct _aLeaf {
        bool operator<(const _aLeaf &) const { return false; }
    };
    struct _aNode1 {
        std::shared_ptr<atree<T1>> p1_;
        T1 p2_;
        std::shared_ptr<atree<T1>> p3_;

        atree<T1> p1() const { return *p1_; }
        const T1 &p2() const { return p2_; }
        atree<T1> p3() const { return *p3_; }

        bool operator<(const _aNode1 &rhs) const {
            return std::tie(*p1_, p2_, *p3_) < std::tie(*rhs.p1_, rhs.p2_, *rhs.p3_);
        }
    };

    std::variant<_aLeaf, _aNode1> value_;
    atree(const std::variant<_aLeaf, _aNode1> &value) : value_(value) {}

  public:
    atree() = default;

    static atree<T1> aLeaf() {
        return atree<T1> { _aLeaf {  } };
    }
    static atree<T1> aNode1(const atree<T1> &p1, const T1 &p2, const atree<T1> &p3) {
        return atree<T1> { _aNode1 { std::make_shared<atree<T1>>(p1), p2, std::make_shared<atree<T1>>(p3) } };
    }

    bool is_aLeaf() const { return std::holds_alternative<_aLeaf>(value_); }
    bool is_aNode1() const { return std::holds_alternative<_aNode1>(value_); }

    const _aNode1 &as_aNode1() const { return std::get<_aNode1>(value_); }

    bool operator<(const atree<T1> &rhs) const { return value_ < rhs.value_; }
};



std::uint64_t add(const std::uint64_t &arg1, const std::uint64_t &arg2);

template<typename T1>
std::deque<T1> app(std::deque<T1> arg1, std::deque<T1> arg2) {
    // app Nil ys = ys
    if (arg1.empty()) {
        return arg2;
    }

    // app (Cons x xs) ys = Cons x (app xs ys)
    auto x = arg1.front();
    arg1.erase(arg1.begin(), arg1.begin() + 1);
    auto xs = std::move(arg1);
    auto temp0 = std::move(xs);
    auto temp1 = std::move(arg2);
    auto temp2 = app(std::move(temp0), std::move(temp1));
    temp2.push_front(x);
    return temp2;
}

template<typename T1>
std::deque<T1> rev(std::deque<T1> arg1) {
    // rev Nil = Nil
    if (arg1.empty()) {
        return std::deque<T1>();
    }

    // rev (Cons x xs) = app (rev xs) (Cons x Nil)
    auto x = arg1.front();
    arg1.erase(arg1.begin(), arg1.begin() + 1);
    auto xs = std::move(arg1);
    auto temp1 = std::move(xs);
    auto temp0 = rev(std::move(temp1));
    auto temp3 = std::deque<T1>();
    temp3.push_front(x);
    auto temp2 = std::move(temp3);
    return app(std::move(temp0), std::move(temp2));
}

std::uint64_t natofsnat(const std::uint64_t &arg1);

std::uint64_t snatofnat(const std::uint64_t &arg1);

template<typename T1>
std::set<T1> testset(std::deque<T1> arg1) {
    // testset Nil = {}
    if (arg1.empty()) {
        return std::set<T1>{};
    }

    // testset (x # xs) = {x} \<inter> testset(xs)
    if (arg1.size() >= 1) {
        auto x = arg1.front();
        arg1.erase(arg1.begin(), arg1.begin() + 1);
        auto xs = std::move(arg1);
        auto temp0 = std::move(xs);
        auto temp1 = std::set<T1>{x};
        auto temp2 = testset(std::move(temp0));
        temp1.merge(temp2);
        return temp2;
    }

    // testset (x # xs) = {x} \<union> testset(xs)
    auto x = arg1.front();
    arg1.erase(arg1.begin(), arg1.begin() + 1);
    auto xs = std::move(arg1);
    auto temp0 = std::move(xs);
    auto temp1 = std::set<T1>{x};
    auto temp2 = testset(std::move(temp0));
    temp1.merge(temp2);
    return temp1;
}

std::uint64_t fib(const std::uint64_t &arg1);

std::uint64_t sfib(const std::uint64_t &arg1);

std::deque<std::uint64_t> merge(std::deque<std::uint64_t> arg1, std::deque<std::uint64_t> arg2);

std::deque<std::uint64_t> merge_sort(std::deque<std::uint64_t> arg1);

// generated by HOL2Cpp
