#include <cstdint>
#include <cstdlib>
#include <map>
#include <utility>



std::uint64_t two_fib(std::uint64_t arg1);

std::uint64_t three_fib(std::uint64_t arg1);

std::uint64_t four_fib(std::uint64_t arg1);

std::uint64_t Jacobsthal(std::uint64_t arg1);

std::uint64_t Narayana(std::uint64_t arg1);

std::uint64_t Leonardo(std::uint64_t arg1);

std::uint64_t Padua(std::uint64_t arg1);

std::uint64_t Pell(std::uint64_t arg1);

std::uint64_t Lucas(std::uint64_t arg1);

// generated by HOL2Cpp
