#include "rule_type.hpp"

std::deque<std::int64_t> supto(const std::int64_t &arg1, const std::int64_t &arg2) {
    // supto i j = (if i \<ge> j then [] else i # supto (i + 1) j)
    auto i = arg1;
    auto j = arg2;
    std::deque<std::int64_t> temp0;
    if (i >= j) {
        temp0 = std::deque<std::int64_t>();
    } else {
        auto temp1 = supto(i + 1, std::move(j));
        temp1.push_front(i);
        temp0 = std::move(temp1);
    }
    return temp0;
}

// generated by HOL2Cpp
