#include "defi_slist.hpp"

std::uint64_t natofsnat(snat arg1) {
    // natofsnat sZero = 0
    if (arg1.is_sZero()) {
        return 0;
    }

    // natofsnat (sSuc n) = (natofsnat n) + 1
    auto n = std::move(arg1.as_sSuc().p1_);
    return natofsnat(std::move(n)) + 1;
}

snat snatofnat(std::uint64_t arg1) {
    // snatofnat 0 = sZero
    if (arg1 == 0) {
        return snat::sZero();
    }

    // snatofnat (Suc n) = sSuc (snatofnat n)
    auto n = arg1 - 1;
    auto temp0 = snat::sSuc(
        snatofnat(std::move(n))
    );
    return temp0;
}

// generated by HOL2Cpp
